/*
 * RearPanel.java
 *
 * Created on December 10, 2006, 8:09 PM
 */

package com.family.solitaire.ui;

/**
 *
 * @author  Aaron
 */
public class RearPanel extends javax.swing.JPanel {
    
    /** Creates new form RearPanel */
    public RearPanel() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        ok = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        javax.swing.ButtonGroup group = new javax.swing.ButtonGroup();

        index = ImageStore.instance().getRearIndex();
        java.awt.Image[] images = ImageStore.instance().getRearImages();
        radios = new ImageRadioButton[images.length];
        for (int i=0; i<images.length; i++) {
            radios[i] = new ImageRadioButton(images[i]);
            if (i == index) {
                radios[i].setSelected(true);
            }
            mainPanel.add(radios[i]);
            group.add(radios[i]);
        }

        ok.setText("OK");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });

        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        mainPanel.setLayout(new java.awt.GridLayout(2, 5, 10, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ok, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ok)
                    .addComponent(cancel))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cancel, ok});

    }// </editor-fold>//GEN-END:initComponents

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        isok = false;
        radios[index].setSelected(true);
        getTopLevelAncestor().setVisible(false);
    }//GEN-LAST:event_cancelActionPerformed

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        for (int i=0; i<radios.length; i++) {
            if (radios[i].isSelected()) {
                index = i;
                ImageStore.instance().setRearIndex(i);
                break;
            }
        }
        isok = true;
        getTopLevelAncestor().setVisible(false);
    }//GEN-LAST:event_okActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton ok;
    // End of variables declaration//GEN-END:variables
    
    boolean isok;
    private int index;
    private ImageRadioButton[] radios;
}
