/*
 * HelpDialog.java
 *
 * Created on December 11, 2006, 11:11 PM
 */

package com.family.help;

import java.io.File;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.xml.parsers.SAXParser;
import javax.xml.parsers.SAXParserFactory;

/**
 *
 * @author  Aaron
 */
public class HelpDialog extends javax.swing.JDialog {
    
    /** Creates new form HelpDialog */
    public HelpDialog(java.awt.Frame parent, boolean modal, String appName) {
        super(parent, modal);
        this.appName = appName;
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tree = new javax.swing.JTree();
        try {
            SAXParser parser = SAXParserFactory.newInstance().newSAXParser();
            HelpHandler handler = new HelpHandler();
            HelpDialog.class.getPackage();
            parser.parse(HelpDialog.class.getClassLoader().
                getSystemResourceAsStream(PATH+"help.xml"), handler);
            tree.setModel(new DefaultTreeModel(handler.getNodes()));
        } catch(Exception e) {
            e.printStackTrace();
        }
        jScrollPane2 = new javax.swing.JScrollPane();
        htmlPane = new javax.swing.JEditorPane();
        try {
            DefaultMutableTreeNode n = (DefaultMutableTreeNode)tree.getModel().getRoot();
            String url = ((NodeInfo)((DefaultMutableTreeNode)tree.getModel().getChild(n, 0)).getUserObject()).url;
            htmlPane.setPage(HelpDialog.class.getClassLoader().getResource(
                PATH + url));
    } catch (Exception e) {
        e.printStackTrace();
    }

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("About " + appName);
    jSplitPane1.setDividerLocation(150);
    tree.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
        public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
            treeValueChanged(evt);
        }
    });

    jScrollPane1.setViewportView(tree);

    jSplitPane1.setLeftComponent(jScrollPane1);

    htmlPane.setEditable(false);
    jScrollPane2.setViewportView(htmlPane);

    jSplitPane1.setRightComponent(jScrollPane2);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
            .addContainerGap())
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
            .addContainerGap())
    );
    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void treeValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_treeValueChanged
        DefaultMutableTreeNode node = (DefaultMutableTreeNode)
                           tree.getLastSelectedPathComponent();

        if (node == null) return;

        NodeInfo nodeInfo = (NodeInfo)node.getUserObject();
        if (nodeInfo.url != null) {
            try {
                htmlPane.setPage(HelpDialog.class.getClassLoader().getResource(
                        PATH + nodeInfo.url));
            } catch (java.io.IOException e) {
                htmlPane.setText("File Not Found!");
                e.printStackTrace();
            }
        }
        
    }//GEN-LAST:event_treeValueChanged
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane htmlPane;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTree tree;
    // End of variables declaration//GEN-END:variables
    
    private String appName;
    private static final String PATH = "com/family/help/";
}
